<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <!-- Meta Tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="Description" content="A melhor Loja de roupas T-Shirts do Brasil">
    <meta name="keywords" content="Loja, virtual, e-commerce, desconto, promoções, roupas, femino, masculino">
    <meta name="author" content="MatheusDev47">
    <meta property=”og:type” content=”website”>
    <meta property=”og:title” content="Orquídea Flor">
    <!-- Icon site -->
    <link rel="icon" href="">
    <!-- Normalize CSS -->
    <link rel="stylesheet" href="CSS/normalize.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="CSS/style.css">
    <!-- Logo Font -->
    <link href="https://fonts.googleapis.com/css2?family=Beau+Rivage&display=swap" rel="stylesheet">
    <!-- Custom Font -->
    <link href="https://fonts.googleapis.com/css2?family=Beau+Rivage&family=Open+Sans:ital,wght@0,300;1,300&display=swap" rel="stylesheet">
    <title>Orquídea Flor</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand p-3">
            <div class="container">
                <a class="navbar-brand logo" href="#" alt="Orquídea flor">Orquídea Flor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <p class="text-dark fs-1">|</p>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-uppercase links">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="#">T-shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Masculino</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Feminino</a>
                        </li>
                    </ul>
                    <form class="d-flex icons-header">
                        <input class="search-field" type="search" placeholder="Buscar" aria-label="Search">
                        <button class="" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <div class="icons-header ms-4">
                        <button class="" id="buttonDropdown">
                            <i class="bi bi-person-circle" alt="Conta"></i>
                            <ul class="menu-dropdown list-group text-uppercase" id="menuDropdown">
                                <li class="list-group-item border-0 d-flex">
                                    <a class="dropdown-item" href="#">
                                        <i class="bi bi-door-open"></i>
                                        Cadastre-se
                                    </a>
                                </li>
                                <li class="list-group-item border-0 d-flex">
                                    <a class="dropdown-item" href="#">
                                        <i class="bi bi-door-open-fill"></i>
                                        Login
                                    </a>
                                </li>
                                <li class="list-group-item border-0 d-flex align-items-center">
                                    <a class="dropdown-item" href="#">
                                        <i class="bi bi-person"></i>
                                        Minha Conta
                                    </a>
                                    
                                </li>
                            </ul>
                        </button>
                        <button class=""><i class="bi bi-cart" alt="Carrinho de compras"></i></button>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <?= $this->content() ?>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Custom JS -->
    <script src="JS/script.js"></script>
</body>

</html>